name: Build
on:
  workflow_dispatch
jobs:
  MacBuild:
    name: Mac Build
    runs-on: macos-latest          
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO_PAT }}  # Generate this Token to give access to private submodules.
      - uses: actions/setup-python@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 8
          distribution: 'adopt'
      - name: Install Boost Mac
        run: brew install boost
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          directory: build
          meson-version: 0.57.2
  UbuntuBuild:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO_PAT }}  # Generate this Token to give access to private submodules.
      - uses: actions/setup-python@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 8
          distribution: 'adopt'
      - name: Install Boost
        run: |
          sudo apt update
          sudo apt install libboost-all-dev
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          directory: build
          meson-version: 0.57.2
  WindowsBuild:
    name: Windows Build
    runs-on: windows-latest          
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO_PAT }}  # Generate this Token to give access to private submodules.
      - uses: actions/setup-python@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 8
          distribution: 'adopt'
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        env:
          cacheName: "boost_1_75_0-msvc-14.2"
        with:
          path: C:\hostedtoolcache\windows\Boost\1.72.0\x86_64
          key: ${{ env.cache-name }}
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'false'
        run: |
          $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.75.0/boost_1_75_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          directory: build
          meson-version: 0.57.2
      
    
